import 'package:siyaha_plus_mobile/models/localTourModel.dart';

final List<LocalTour> mockLocalTours = [
  LocalTour(
    tourName: 'City Exploration Tour',
    companyName: 'City Adventures',
    description: 'Explore the heart of the city with a guided tour that takes you to the most iconic landmarks.',
    imageUrl: 'https://images.unsplash.com/photo-1567571651702-292f678dd7f0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzNjUyOXwwfDF8c2VhcmNofDEwfHxjaXR5JTIwdG91ciUyMGVtYmV8ZW58MHx8fHwxNjgzMTQwMTg5&ixlib=rb-4.0.3&q=80&w=400',
    price: 120.0,
    duration: 4, // Duration in hours
    location: 'Paris',
    availableDates: ['2024-11-01', '2024-11-15', '2024-12-01'],
    highlights: ['Eiffel Tower', 'Louvre Museum', 'Notre-Dame Cathedral'],
    companyLogoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Logo_Science_Adventure.svg/512px-Logo_Science_Adventure.svg.png',
    companyProfilePicUrl: 'https://randomuser.me/api/portraits/men/1.jpg',
    plans: [
      TourPlan(planName: 'Standard Tour', price: 120.0, duration: 4, description: 'A guided tour of the city\'s main attractions.'),
      TourPlan(planName: 'Premium Tour', price: 180.0, duration: 6, description: 'Includes lunch and skip-the-line access to major attractions.'),
    ],
  ),
  LocalTour(
    tourName: 'Mountain Adventure Tour',
    companyName: 'Mountain Expeditions',
    description: 'A thrilling adventure in the mountains with breathtaking views and challenging trails.',
    imageUrl: 'https://images.unsplash.com/photo-1506748686214-28f4e3c693b3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzNjUyOXwwfDF8c2VhcmNofDJ8fG1vdW50YWluJTIwYWR2ZW50dXJlJTIwdG91c3xlbnwwfHx8fDE2ODMxNDAxNzY&ixlib=rb-4.0.3&q=80&w=400',
    price: 150.0,
    duration: 6,
    location: 'Colorado',
    availableDates: ['2024-11-15', '2024-12-10'],
    highlights: ['Rock Climbing', 'Mountain Trails', 'Wildlife Sightings'],
    companyLogoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Logo_Science_Adventure.svg/512px-Logo_Science_Adventure.svg.png',
    companyProfilePicUrl: 'https://randomuser.me/api/portraits/men/2.jpg',
    plans: [
      TourPlan(planName: 'Basic Adventure', price: 150.0, duration: 6, description: 'Includes guided hikes and rock climbing lessons.'),
      TourPlan(planName: 'All-Inclusive Adventure', price: 250.0, duration: 8, description: 'Includes meals, accommodation, and all activities.'),
    ],
  ),
  LocalTour(
    tourName: 'Desert Safari',
    companyName: 'Desert Adventures',
    description: 'Experience the thrill of a desert safari with dune bashing and camel riding.',
    imageUrl: 'https://images.unsplash.com/photo-1506748686214-67840d4d1136?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzNjUyOXwwfDF8c2VhcmNofDEyfHxkZXNlcnQlMjBzYWZhcmV8ZW58MHx8fHwxNjgzMTQwMTg5&ixlib=rb-4.0.3&q=80&w=400',
    price: 200.0,
    duration: 5,
    location: 'Dubai',
    availableDates: ['2024-11-05', '2024-11-20'],
    highlights: ['Dune Bashing', 'Camel Riding', 'Traditional Dinner'],
    companyLogoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Logo_Science_Adventure.svg/512px-Logo_Science_Adventure.svg.png',
    companyProfilePicUrl: 'https://randomuser.me/api/portraits/men/3.jpg',
    plans: [
      TourPlan(planName: 'Evening Safari', price: 200.0, duration: 5, description: 'Includes dune bashing and BBQ dinner.'),
      TourPlan(planName: 'Overnight Safari', price: 350.0, duration: 12, description: 'Includes overnight camping under the stars and breakfast.'),
    ],
  ),
  LocalTour(
    tourName: 'Cultural Heritage Tour',
    companyName: 'Heritage Travels',
    description: 'Discover the rich cultural heritage and history of the ancient city.',
    imageUrl: 'https://images.unsplash.com/photo-1542831371-dde8b228ce63?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzNjUyOXwwfDF8c2VhcmNofDExfHxjdWx0dXJhbCUyMHRvdXJ8ZW58MHx8fHwxNjgzMTQwMTg5&ixlib=rb-4.0.3&q=80&w=400',
    price: 90.0,
    duration: 3,
    location: 'Rome',
    availableDates: ['2024-11-12', '2024-12-15'],
    highlights: ['Colosseum', 'Vatican City', 'Roman Forum'],
    companyLogoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Logo_Science_Adventure.svg/512px-Logo_Science_Adventure.svg.png',
    companyProfilePicUrl: 'https://randomuser.me/api/portraits/men/4.jpg',
    plans: [
      TourPlan(planName: 'Standard Heritage Tour', price: 90.0, duration: 3, description: 'A guided tour of historical sites.'),
      TourPlan(planName: 'Extended Heritage Tour', price: 150.0, duration: 5, description: 'Includes additional sites and a local guide.'),
    ],
  ),
  LocalTour(
    tourName: 'Tropical Beach Getaway',
    companyName: 'Beach Holidays',
    description: 'Relax on pristine beaches and enjoy water sports in a tropical paradise.',
    imageUrl: 'https://images.unsplash.com/photo-1548948974-4f87e61fc4d4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzNjUyOXwwfDF8c2VhcmNofDV8fGJlYWNoJTIwdG91cmxlJTIwcGFyYWRpc2V8ZW58MHx8fHwxNjgzMTQwMTg5&ixlib=rb-4.0.3&q=80&w=400',
    price: 300.0,
    duration: 7,
    location: 'Bali',
    availableDates: ['2024-11-25', '2024-12-20'],
    highlights: ['Snorkeling', 'Beach Volleyball', 'Sunbathing'],
    companyLogoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Logo_Science_Adventure.svg/512px-Logo_Science_Adventure.svg.png',
    companyProfilePicUrl: 'https://randomuser.me/api/portraits/men/5.jpg',
    plans: [
      TourPlan(planName: 'Standard Beach Package', price: 300.0, duration: 7, description: 'Includes accommodation and meals.'),
      TourPlan(planName: 'Luxury Beach Package', price: 500.0, duration: 10, description: 'Includes luxury accommodation and spa treatments.'),
    ],
  ),
];
